Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", type: "dhcp", name: "vagrantnet-vbox1"
  # Run "VBoxManage list hostonlynets" 
  # to see if you have a network named vagrantnet-vbox1
end
