Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel9"
  config.vm.provider "qemu" do |qe|
    qe.machine = "virt,accel=hvf,highmem=off"
    qe.cpu = "cortex-a72"
    qe.memory = "3072"
    qe.ssh_port = "50023" 
  end
end

