Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provision "shell", path: "setup.sh"
  config.vm.network "private_network", type: "dhcp", name: "vagrantnet-vbox1"
end
