Vagrant.configure("2") do |config|
  # Define first VM
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "bento/ubuntu-22.04"  
    ubuntu1.vm.hostname = "ubuntu1"
    # Verify you have vagrantnet-vbox1 host-only network
    ubuntu1.vm.network "private_network", type: "dhcp", name: "vagrantnet-vbox1"
  end

  # Define second VM
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "bento/ubuntu-22.04"  
    ubuntu2.vm.hostname = "ubuntu2"
    # Verify you have vagrantnet-vbox1 host-only network
    ubuntu2.vm.network "private_network", type: "dhcp", name: "vagrantnet-vbox1"
  end
end
